[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "heart-disease-mlops"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
