name: MLOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint-test-train:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: heart-disease-mlops

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Lint
        run: flake8 src/

      - name: Run tests
        run: pytest

      - name: Train model
        run: python src/train.py

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: heart-disease-mlops/mlruns/

      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: eda-plots
          path: heart-disease-mlops/artifacts/plots/
